#cloud-config
hostname: mbvmboot
timezone: Asia/Taipei

# ✅ 啟用 root 並設定密碼
disable_root: false

chpasswd:
  list: |
    root:!234%
  expire: False

# ✅ 允許密碼登入 SSH（可初始化後關閉）
ssh_pwauth: true

# ✅ 金鑰登入（替換成你自己的 SSH 公鑰）
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCFPSus6XcIqB9s6w995rgV5nx0z35bgl0VinaGhAjBU/X0qLJzfRxIKbbdUuEKpG7VUV3FNNw6haiHjWidsZ63WmgBBBcSPuBRVEYyPwiNWQTq7aIdmys95KPgabqrIgOu38VVA42xeNW4pV5JLD9cdnkJ5KcytSx9LDzZDKvDVByO68aw1izQ3TlGfI9C8aB2QfYxd15UxiNFKvXWXA7uGB9jTXlfgy3wqjDPTxD3xcK3WJrsNw3FU+zizC9xmfAsQvwvXZFsiMCbEAwR0IV2Vgymdm/uzw/uG8sODQ5BTMaIaxGOmsCJUl50YTNkp7aPFenavgilju0f05PLmFaKvXuexyPresHqHHq8O8zLBtYNnK7axx1kzrHY60pUSBwvmfYvqCK5DIOA97S/KjW0XkYyjl80c+VOQrsF6p2/tHE3EHZCcGjUXKPGdZifpHUv33wYdZWWwcub/dFOS34OCdG/KrH0vD3Z9GsnRI2Kh7Wv+c2TAp/xZBVg/5iObj8= root@mbpc220908

package_update: true
package_upgrade: true

# ✅ 預先安裝這些常用套件
packages:
  - tasksel
  - net-tools
  - curl
  - vim
  - git
  - htop
  - python3-pip
  - fail2ban
  - ufw
  - unzip
  - openssh-server

# ✅ 自動重啟安裝中會更新的服務
write_files:
  - path: /etc/needrestart/needrestart.conf
    content: |
      \$nrconf{restart} = 'a';

# ✅ 安裝 Server 套件、啟用 SSH、防火牆
runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - DEBIAN_FRONTEND=noninteractive tasksel install server
  - systemctl enable ssh
  - ufw allow OpenSSH
  - ufw --force enable
  - echo "✅ 初次初始化完成 $(date)" >> /var/log/cloud-init-first.log
